# Pull official Python image
FROM python:3.12-slim

WORKDIR /usr/src/app

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    netcat-openbsd \
    curl \
    postgresql-client \
    libzbar0 \
    && rm -rf /var/lib/apt/lists/*
    
    
# Copy and install Python dependencies
COPY requirements*.txt ./
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy app source
COPY . .

# Make the run_migrations.sh script executable and run it
RUN chmod +x run_migrations.sh && ./run_migrations.sh
    
# Ensure the migration script exits with failure if theres an issue

# Expose the port your app runs on
EXPOSE 8001

# Command to run your app with uvicorn and enable --reload for development
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
